PKG_NAME="RPi"
PKG_VERSION=""
PKG_REV="1"
PKG_ARCH="any"
PKG_LICENSE="various"
PKG_SITE="http://www.openelec.tv"
PKG_URL=""
PKG_DEPENDS_TARGET="toolchain rpi-fbcp"
PKG_PRIORITY="optional"
PKG_SECTION="virtual"
PKG_SHORTDESC="add pyserial"
PKG_LONGDESC="add pyserial"

PKG_IS_ADDON="no"
PKG_AUTORECONF="no"
